#!/usr/bin/env python3
"""Emoji ↔ sarcasm association on the checked-in splits.

Prints support, P(sarc | emoji), and pointwise PMI for the most common faces.
This is the classical justification for keeping a dedicated emoji table.
"""

from __future__ import annotations

import argparse
import math
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from examples.lib.dataset_io import Split, load_all_splits
from examples.lib.emoji_extract import extract_emojis


def pmi(p_joint: float, p_x: float, p_y: float) -> float:
    if p_joint <= 0 or p_x <= 0 or p_y <= 0:
        return float("-inf")
    return math.log2(p_joint / (p_x * p_y))


def analyze(
    split: Split, min_support: int
) -> tuple[list[dict[str, float | str | int]], Counter]:
    n = len(split)
    n_pos = sum(split.labels)
    p_sarc = n_pos / n if n else 0.0
    emoji_rows: dict[str, list[int]] = defaultdict(list)
    pair_counts: Counter[tuple[str, str]] = Counter()

    for text, label in split.pairs():
        emojis = extract_emojis(text)
        unique = list(dict.fromkeys(emojis))
        for emo in unique:
            emoji_rows[emo].append(label)
        for i, a in enumerate(unique):
            for b in unique[i + 1 :]:
                pair_counts[tuple(sorted((a, b)))] += 1

    rows: list[dict[str, float | str | int]] = []
    for emo, labels in emoji_rows.items():
        support = len(labels)
        if support < min_support:
            continue
        pos = sum(labels)
        p_e = support / n
        p_joint = pos / n
        rows.append(
            {
                "emoji": emo,
                "support": support,
                "sarcastic": pos,
                "p_sarc": pos / support,
                "pmi": pmi(p_joint, p_e, p_sarc),
            }
        )
    rows.sort(key=lambda r: (float(r["pmi"]), int(r["support"])), reverse=True)
    return rows, pair_counts


def render(name: str, rows: list[dict], pairs: Counter, top_pairs: int) -> str:
    lines = [
        f"## {name}",
        "",
        "| emoji | support | sarcastic | P(sarc|e) | PMI(e, sarc) |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for row in rows:
        lines.append(
            f"| {row['emoji']} | {row['support']} | {row['sarcastic']} "
            f"| {row['p_sarc']:.3f} | {row['pmi']:.3f} |"
        )
    if pairs:
        lines += ["", f"Top emoji pairs (unique-per-tweet co-occurrence, n={top_pairs}):", ""]
        for (a, b), count in pairs.most_common(top_pairs):
            lines.append(f"- {a} {b}  ({count})")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT / "dataset")
    parser.add_argument("--min-support", type=int, default=25)
    parser.add_argument("--top-pairs", type=int, default=8)
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args(argv)

    splits = load_all_splits(args.root)
    chunks = [
        "# Emoji ↔ sarcasm signals",
        "",
        "Generated by `examples/emoji_signals.py`. PMI is log2 "
        "P(emoji, sarc) / (P(emoji) P(sarc)) on tweet-level unique emoji.",
        "",
    ]
    for name in ("train", "test", "subtest"):
        min_support = args.min_support if name == "train" else max(4, args.min_support // 6)
        rows, pairs = analyze(splits[name], min_support=min_support)
        chunks.append(render(name, rows, pairs, args.top_pairs))
    report = "\n".join(chunks)
    print(report)
    if args.out is not None:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(report, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
